name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create build directories
      run:  |
        mkdir build
        mkdir template/build
    - name: Install Ruby & Ceedling
      run:  |
        sudo apt-get install ruby
        sudo gem install ceedling
        sudo python -m pip install gcovr
    - name: Configure Lib CMake
      run: cd build && cmake ..
    - name: Build lib
      run: cd build && make
    - name: Configure Demo CMake
      run: cd template/build && cmake ..
    - name: Build Demo
      run: cd template/build && make
    - name: Run Unit tests
      run: cd build && make tests
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_MCP342X_TOKEN }}
        name: CodeCov-MCP342x # optional
        files: ./build/artifacts/gcov/GcovCoverageCobertura.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)